# Generated by Django 5.1.15 on 2026-09-20 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('regional_names', models.TextField(blank=True, help_text='Common Indian or vernacular names')),
                ('summary', models.TextField(blank=True, help_text='Source description of this food item')),
                ('category', models.CharField(blank=True, help_text='grain, pulse, vegetable, fruit, dairy, nut_seed, spice, oil', max_length=100)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('diet_types', models.JSONField(blank=True, default=list, help_text="['vegan', 'vegetarian', 'non-vegetarian']")),
                ('meal_types', models.JSONField(blank=True, default=list, help_text="['breakfast', 'lunch', 'dinner', 'snack']")),
                ('seasons', models.JSONField(blank=True, default=list, help_text="['summer', 'monsoon', 'winter', 'spring', 'autumn']")),
                ('weather_categories', models.JSONField(blank=True, default=list, help_text="['HOT', 'VERY_HOT', 'COOL', 'COLD', 'HUMID', 'RAINY']")),
                ('preparation_methods', models.TextField(blank=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('chapter', models.CharField(blank=True, max_length=255)),
                ('source_url', models.TextField(blank=True)),
                ('original_text', models.TextField(blank=True, help_text='Direct excerpt citation from the book/website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='documents.source')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='core.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100)),
                ('recommendation_type', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('AVOID', 'Avoid'), ('LIMIT', 'Limit')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.food')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField()),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active')], default='moderate', max_length=20)),
                ('diet_type', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non-Vegetarian')], default='vegetarian', max_length=50)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('disliked_foods', models.JSONField(blank=True, default=list)),
                ('disliked_ingredients', models.JSONField(blank=True, default=list)),
                ('disliked_categories', models.JSONField(blank=True, default=list)),
                ('liked_foods', models.JSONField(blank=True, default=list)),
                ('liked_ingredients', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('location_auto_detected', models.BooleanField(default=False)),
                ('cant_make', models.JSONField(blank=True, default=list)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
