# Generated by Django 5.1.15 on 2026-09-20 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedMealPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=20)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('weather_category', models.CharField(blank=True, max_length=20)),
                ('target_condition', models.CharField(blank=True, max_length=100)),
                ('rationale', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citation_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.source')),
                ('foods', models.ManyToManyField(related_name='learned_patterns', to='core.food')),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_boost', models.IntegerField(default=0)),
                ('times_recommended', models.IntegerField(default=1)),
                ('times_accepted', models.IntegerField(default=0)),
                ('times_rejected', models.IntegerField(default=0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'food')},
            },
        ),
    ]
