# Generated by Django 5.1.15 on 2026-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learnedmealpattern_userfoodaffinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
